name: Deploy Environment
on:
  push:
    branches: [ develop ]
    
jobs:
  Development:
    runs-on: self-hosted
    environment: Development
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Deploy
      uses: ./.github/actions
      with:
        environment: Development
        aws_role_to_assume: ""
        artifact_name: np-s3-eb-deployment
        aws_region: ca-central-1

  # Production:
  #   runs-on: hosted-runner
  #   environment: Production
  #   steps:
  #   - name: Checkout source code
  #     uses: actions/checkout@v3
  #     with:
  #       token: ${{ secrets.GH_TOKEN }}
  #       submodules: true

  #   - name: Deploy
  #     uses: ./.github/actions/deploy.yml
  #     with:
  #       environment: Production
  #       account_id: ${{ env.aws_account_id}}
  #       account_name: awsaccountprod
  #       artifact_name: prod-s3-eb-deployment
  #       region: ca-central-1
    